import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/global.css';
import ThemeLayout from '@/components/layouts/ThemeLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeLayout>{children}</ThemeLayout>
      </body>
    </html>
  );
}
